# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'doctor_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from controllers import controller_doctors


class Ui_add_doctor_form(object):
    def setupUi(self, add_doctor_form):
        add_doctor_form.setObjectName("add_doctor_form")
        add_doctor_form.resize(364, 223)
        self.doctor_info = QtWidgets.QGroupBox(add_doctor_form)
        self.doctor_info.setGeometry(QtCore.QRect(10, 10, 341, 201))
        self.doctor_info.setObjectName("doctor_info")
        self.instructions_add_doctor = QtWidgets.QLabel(self.doctor_info)
        self.instructions_add_doctor.setGeometry(QtCore.QRect(10, 20, 281, 16))
        self.instructions_add_doctor.setObjectName("instructions_add_doctor")
        self.text_nombre_completo = QtWidgets.QLabel(self.doctor_info)
        self.text_nombre_completo.setGeometry(QtCore.QRect(10, 60, 91, 16))
        self.text_nombre_completo.setObjectName("text_nombre_completo")
        self.text_especializacion = QtWidgets.QLabel(self.doctor_info)
        self.text_especializacion.setGeometry(QtCore.QRect(20, 90, 71, 16))
        self.text_especializacion.setObjectName("text_especializacion")
        self.text_dni = QtWidgets.QLabel(self.doctor_info)
        self.text_dni.setGeometry(QtCore.QRect(70, 120, 21, 16))
        self.text_dni.setObjectName("text_dni")
        self.doctor_name = QtWidgets.QLineEdit(self.doctor_info)
        self.doctor_name.setGeometry(QtCore.QRect(100, 60, 201, 20))
        self.doctor_name.setObjectName("doctor_name")
        self.specialty = QtWidgets.QLineEdit(self.doctor_info)
        self.specialty.setGeometry(QtCore.QRect(100, 90, 201, 20))
        self.specialty.setObjectName("specialty")
        self.dni = QtWidgets.QLineEdit(self.doctor_info)
        self.dni.setGeometry(QtCore.QRect(100, 120, 201, 20))
        self.dni.setObjectName("dni")
        self.button_add_doctor = QtWidgets.QPushButton(self.doctor_info)
        self.button_add_doctor.setGeometry(QtCore.QRect(240, 170, 91, 23))
        self.button_add_doctor.setObjectName("button_add_doctor")
        self.button_add_doctor.clicked.connect(self.get_doctor_info)

        self.retranslateUi(add_doctor_form)
        QtCore.QMetaObject.connectSlotsByName(add_doctor_form)

    def retranslateUi(self, add_doctor_form):
        _translate = QtCore.QCoreApplication.translate
        add_doctor_form.setWindowTitle(_translate("add_doctor_form", "Añadir doctor(a)"))
        self.doctor_info.setTitle(_translate("add_doctor_form", "Información del doctor(a)"))
        self.instructions_add_doctor.setText(_translate("add_doctor_form", "Por favor ingrese los datos de nuestro nuevo integrante"))
        self.text_nombre_completo.setText(_translate("add_doctor_form", "Nombre completo"))
        self.text_especializacion.setText(_translate("add_doctor_form", "Especialización"))
        self.text_dni.setText(_translate("add_doctor_form", "DNI"))
        self.button_add_doctor.setText(_translate("add_doctor_form", "Añadir doctor(a)"))

    def show_message(self, message, type_message):
        msg = QMessageBox()
        msg.setText(message)
        msg.setIcon(type_message)
        msg.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)
        retval = msg.exec_()

    def get_doctor_info(self):
        doctor_name = self.doctor_name.text().strip()
        doctor_dni = self.dni.text().strip()
        doctor_specialty = self.specialty.text().strip()

        if not (doctor_name and doctor_dni and doctor_specialty):
            self.show_message("El doctor(a) no pudo ser agregado(a), intente de nuevo.", QMessageBox.Critical)
        else:
            # pasar esto a controlador
            self.show_message("El doctor(a) ha sido agregado(a)!", QMessageBox.Information)
            controller_doctors.create_doctor(name=doctor_name, dni=doctor_dni, specialty=doctor_specialty)
            self.doctor_name.clear()
            self.dni.clear()
            self.specialty.clear()


