# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hospital_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from controllers import controller_hospital


class Ui_add_hospital_form(object):
    def setupUi(self, add_hospital_form):
        add_hospital_form.setObjectName("add_hospital_form")
        add_hospital_form.resize(397, 149)

        self.hospital_info = QtWidgets.QGroupBox(add_hospital_form)
        self.hospital_info.setGeometry(QtCore.QRect(10, 10, 381, 131))
        self.hospital_info.setObjectName("hospital_info")

        self.text_hospital_name = QtWidgets.QLabel(self.hospital_info)
        self.text_hospital_name.setGeometry(QtCore.QRect(10, 60, 101, 16))
        self.text_hospital_name.setObjectName("text_hospital_name")

        self.hospital_name = QtWidgets.QLineEdit(self.hospital_info)
        self.hospital_name.setGeometry(QtCore.QRect(110, 60, 211, 20))
        self.hospital_name.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.hospital_name.setText("")
        self.hospital_name.setObjectName("hospital_name")

        self.instructions_add_hospital = QtWidgets.QLabel(self.hospital_info)
        self.instructions_add_hospital.setGeometry(QtCore.QRect(10, 20, 331, 16))
        self.instructions_add_hospital.setObjectName("instructions_add_hospital")

        self.button_add_hospital = QtWidgets.QPushButton(self.hospital_info)
        self.button_add_hospital.setGeometry(QtCore.QRect(294, 100, 81, 23))
        self.button_add_hospital.setObjectName("button_add_hospital")
        self.button_add_hospital.clicked.connect(self.get_hospital_name)

        self.retranslateUi(add_hospital_form)
        QtCore.QMetaObject.connectSlotsByName(add_hospital_form)

    def retranslateUi(self, add_hospital_form):
        _translate = QtCore.QCoreApplication.translate
        add_hospital_form.setWindowTitle(_translate("add_hospital_form", "Añadir hospital"))
        self.hospital_info.setTitle(_translate("add_hospital_form", "Datos del hospital"))
        self.text_hospital_name.setText(_translate("add_hospital_form", "Nombre del hospital"))
        self.instructions_add_hospital.setText(_translate("add_hospital_form", "Por favor ingrese el nombre del nuevo hospital."))
        self.button_add_hospital.setText(_translate("add_hospital_form", "Añadir hospital"))

    def show_message(self, message, type_message):
        msg = QMessageBox()
        msg.setText(message)
        msg.setIcon(type_message)
        msg.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)
        retval = msg.exec_()

    def get_hospital_name(self):
        hospital_name = self.hospital_name.text().strip()

        if not hospital_name:
            self.show_message("El hospital no pudo ser agregado, intente de nuevo.", QMessageBox.Critical)
        else:
            # pasar esto a controlador
            self.show_message("¡Hospital agregado!", QMessageBox.Information)
            controller_hospital.create_hospital(name=hospital_name)
            self.hospital_name.clear()




