# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'search_doctor_name.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import doctor_info_window

class Ui_doctor_search_form(object):
    def setupUi(self, doctor_search_form):
        doctor_search_form.setObjectName("doctor_search_form")
        doctor_search_form.resize(378, 107)

        self.instructions_search_doctor = QtWidgets.QLabel(doctor_search_form)
        self.instructions_search_doctor.setGeometry(QtCore.QRect(10, 10, 291, 16))
        self.instructions_search_doctor.setObjectName("instructions_search_doctor")

        self.text_full_name = QtWidgets.QLabel(doctor_search_form)
        self.text_full_name.setGeometry(QtCore.QRect(10, 40, 91, 16))
        self.text_full_name.setObjectName("text_full_name")

        self.doctor_name = QtWidgets.QLineEdit(doctor_search_form)
        self.doctor_name.setGeometry(QtCore.QRect(100, 40, 241, 20))
        self.doctor_name.setObjectName("doctor_name")

        self.button_search_doctor_name = QtWidgets.QPushButton(doctor_search_form)
        self.button_search_doctor_name.setGeometry(QtCore.QRect(300, 80, 71, 23))
        self.button_search_doctor_name.setObjectName("button_search_doctor_name")
        self.button_search_doctor_name.clicked.connect(self.search_doctor_name)

        self.retranslateUi(doctor_search_form)
        QtCore.QMetaObject.connectSlotsByName(doctor_search_form)

    def retranslateUi(self, doctor_search_form):
        _translate = QtCore.QCoreApplication.translate
        doctor_search_form.setWindowTitle(_translate("doctor_search_form", "Buscar doctor(a) por nombre"))
        self.instructions_search_doctor.setText(_translate("doctor_search_form", "Por favor ingre el nombre completo del doctor(a) que busca"))
        self.text_full_name.setText(_translate("doctor_search_form", "Nombre completo"))
        self.button_search_doctor_name.setText(_translate("doctor_search_form", "Buscar"))

    def show_message(self, message, type_message):
        msg = QMessageBox()
        msg.setText(message)
        msg.setIcon(type_message)
        msg.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)
        retval = msg.exec_()

    def search_doctor_name(self):
        doctor_name = self.doctor_name.text().strip()

        if not doctor_name:
            self.show_message("No ha ingresado un nombre, por favor intentelo de nuevo.", QMessageBox.Critical)
        else:
            self.doctor_window_table = QtWidgets.QMainWindow()
            self.ui_doctor_window = doctor_info_window.Ui_doctor_info_window()
            self.ui_doctor_window.setupUi(self.doctor_window_table)
            self.ui_doctor_window.get_doctor_by_name(doctor_name)
            self.doctor_window_table.show()

